### ISSUE TITLE
Actvatevirtualkeyboard function does not operate inside renderUI function of shiny

### ISSUE THREAD

**Issue by atmajitg** [Emelieh21/shinykeyboard#1]
Hi Emelieh,

Thank you for the wonderful package. While working with shinykeyboard I noted that the activateVirtualKeyboard() does not work when placed inside a renderUI() function of shiny. Would you know if there is an easy fix or workaround?

Thank you.

Regards,
Atmajit

**Comment by Emelieh21** [comment]
Hey Atmajit,

Thanks so much! Really nice to know someone is using the package :) I'd have to look into it again, I'm hoping to have some time for that this weekend. Is there any specific reason why you want to place the activateVirtualKeyboard() inside the renderUI() and not in the fluidPage() (or any other kind of page)? Just curious to know what is the particular use case

**Comment by atmajitg** [comment]
Apologize for the delay in responding to your question.

I am creating a shiny application that allows user to take Math assessment/exam. So I have questions which are multiple choice (use radio button widget) and questions which are Text (Text Input widget). So to achieve this i am using renderUI in serve.R file to display these two type of questions. Now for Text based questions i want to allow students to type math symbols such as square root, cube root, pi etc for their answers.

My plan is to use the keyboard for math symbols (such as exponent, square root symbols, pi symbols etc) by editing the javascript file in your package. This works well. The issue is that when I load the package the keyboard does not show up when I use it inside the renderUI function.  

Thank you for your response .

**Comment by Emelieh21** [comment]
Hi Atmajit,

Thanks for explaining your use case and sorry for not reacting earlier. I hope you managed to get your math exam app to work well. In case it's still relevant, I just made a small update that should simplify attaching the keyboard to textInputs that are created at the server side of the app. With the latest version of this package and shinyjs installed, the following should work:

```
library(shiny)
library(shinyjs)
library(shinykeyboard)
library(shinydashboard)

textIds = c("text1", "text2")
keyboard <- generateVirtualKeyboard(textIds)

ui <- dashboardPage(
  dashboardHeader(title = "Quick Example"),
  dashboardSidebar(textInput("text1", "Text 1")),
  dashboardBody(
    useShinyjs(),
    activateVirtualKeyboard(keyboard),
    textInput("text2", "Text 2"),
    textOutput("content1"),
    textOutput("content2"),
    uiOutput("main_input")
  )
)
server <- function(input, output) {
  output$main_input <- renderUI({
    isolate({
      fluidRow(
        column(width = 6, textInput(inputId = "text3", label = "Text 3")),
        column(width = 6, textInput(inputId = "text4", label = "Text 4"))
      )
    })
  })
  # Make keyboard bind to new inputs
  observeEvent({input$text3
                input$text4}, {
      shinyjs::runjs(updateKeyboard(c("text3","text4")))
    })
  output$content1 <- renderText({
    paste0(input$text1)
  })
  output$content2 <- renderText({
    paste0(input$text2)
  })
}
shinyApp(ui, server)
```
Thanks again for reporting the issue!
